services:
  nginx-proxy:
    image: "nginxproxy/nginx-proxy:${TAG:-alpine}"
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "${VOL_HTML:-html}:/usr/share/nginx/html"
      - "${VOL_CERTS:-certs}:/etc/nginx/certs"
      - "${VOL_VHOSTS:-vhosts}:/etc/nginx/vhost.d"
    environment:
      - DEFAULT_HOST="${HOST_DEFAULT:-local.khem.io}"
    networks:
      - nginx
  nginx-acme:
    image: "nginxproxy/acme-companion:${TAG:-alpine}"
    container_name: nginx-acme
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "${VOL_HTML:-html}:/usr/share/nginx/html"
      - "${VOL_CERTS:-certs}:/etc/nginx/certs"
      - "${VOL_VHOSTS:-vhosts}:/etc/nginx/vhost.d"
      - "${VOL_ACME:-acme}:/etc/acme.sh"
    environment:
      - DEFAULT_EMAIL="${EMAIL_DEFAULT:-ops@khemlab.com}"
    networks:
      - nginx      

volumes:
 html:
 certs:
 vhosts:
 acme:

networks:
 nginx:
   drupal:
     name: '${NETWORK_NAME:-default}'
     external: '${NETWORK_EXTERNAL:-true}'
     driver: '${NETWORK_DRIVER:-bind}'